// <auto-generated />
using Mango.Service.CouponAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Service.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Service.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CounponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounponId"));

                    b.Property<string>("CounponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.HasKey("CounponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CounponId = 1,
                            CounponCode = "10OFF",
                            DiscountAmount = 10.0
                        },
                        new
                        {
                            CounponId = 2,
                            CounponCode = "20OFF",
                            DiscountAmount = 20.0
                        },
                        new
                        {
                            CounponId = 3,
                            CounponCode = "30OFF",
                            DiscountAmount = 30.0
                        },
                        new
                        {
                            CounponId = 4,
                            CounponCode = "40OFF",
                            DiscountAmount = 40.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
